name: pys4
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy
  - suitesparse 
  - openblas 
  - mpich 
  - boost 
  - fftw 
  - cxx-compiler
  - c-compiler
  - imagemagick
  - povray
  - ghostscript
