name: Test Conda
run-name: Test Conda
on: [push]
jobs:
  test:
    name: test Mamba
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      # - uses: conda-incubator/setup-miniconda@v3
      #   with:
      #     python-version: 3.12
      #     mamba-version: "*"
      #     channels: conda-forge,defaults
      #     channel-priority: true
      #     activate-environment: anaconda-client-env
      #     environment-file: environment.yml
      # - shell: bash -el {0}
      #   run: |
      #     conda info
      #     conda list
      #     conda config --show-sources
      #     conda config --show
      #     printenv | sort
      # - shell: bash -el {0}
      #   run: |
      #     pip install .
      #     make check
      #     pip install pytest
      #     make test
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        #, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl