name: Test
run-name: ${{ github.repository }} testing
on: [push]
jobs:
  install-and-test:
    name: system (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-24.04] #, windows-latest
    runs-on: ${{ matrix.os }}
    env:
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install system packages
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends  \
          gcc g++ pkg-config cmake \
          libsuitesparse-dev liblapack-dev libopenblas-dev libfftw3-dev libfabric-dev mpich \
          libboost-serialization-dev libboost-mpi-dev imagemagick povray ghostscript 
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and run tests
        run: |
          pip install .[test] -v
          pytest

  install-and-test-conda:
    name: conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    env:
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Install package and run tests
        shell: bash -el {0}
        run: |
          mamba create -n pys4 python=${{ matrix.python-version }} -c conda-forge
          mamba env update -n pys4 -f environment.yml
          conda activate pys4
          pip install .[test] -v -Csetup-args="-Dconda=true"
          pytest